---
kind: pipeline
type: docker
name: build

trigger:
  event:
    - pull_request

steps:
  - name: Build
    image: debian:11-slim
    commands:
      - apt-get update
      - apt-get install -y curl openssh-client
      - curl -L https://github.com/rust-lang/mdBook/releases/download/v0.4.27/mdbook-v0.4.27-x86_64-unknown-linux-gnu.tar.gz > mdbook.tar.gz
      - tar xzf mdbook.tar.gz
      - ./mdbook build

---
kind: pipeline
type: docker
name: build and deploy

trigger:
  branch:
    - main
  event:
    - push

steps:
  - name: Build
    image: debian:11-slim
    environment:
      SSH_DEPLOY_KEY:
        from_secret: ssh_deploy_key
    commands:
      - apt-get update
      - apt-get install -y curl openssh-client
      - curl -L https://github.com/rust-lang/mdBook/releases/download/v0.4.27/mdbook-v0.4.27-x86_64-unknown-linux-gnu.tar.gz > mdbook.tar.gz
      - tar xzf mdbook.tar.gz
      - ./mdbook build
      - eval `ssh-agent -s`
      - echo "$${SSH_DEPLOY_KEY}" | tr -d '\r' | ssh-add - > /dev/null
      - scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r book/* constellation@cygnus.constellations.zone:/var/www/book.constellations.zone/html/
